# Generated by Django 4.2.10 on 2024-08-20 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='group_students', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
